---
# see: https://docs.github.com/en/code-security/dependabot/dependabot-security-updates
# see: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
    groups:
      # jupyter-dependencies:
      #   patterns:
      #     - jupyterlab
      #     - notebook
      dev-dependencies:
        dependency-type: development
    ignore:
      # ignore all patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    # ignore:
    #   - dependency-name: "botocore"
    #   - dependency-name: "mistune"
    #   - dependency-name: "urllib3"
    #   - dependency-name: "cryptography"
    #   - dependency-name: "paramiko"
    #   - dependency-name: "rsa"
