[tool.poetry]
name = "bms-monitor-sam"
version = "0.2.0"
description = ""
authors = ["Yukihiro Okada <yuokada@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.18.48"
python-twitter = "^3.5"
requests = "2.24.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
