[tool.poetry]
authors = ["Yukihiro Okada <yuokada@users.noreply.github.com>"]
description = ""
license = "MIT"
name = "bms-monitor-sam"
version = "0.2.0"

[tool.poetry.dependencies]
boto3 = "^1.26.41"
python = "^3.9"
requests = "^2.25"
urllib3 = "<2"

[tool.poetry.group.dev.dependencies]
aws-sam-cli = "^1.100.0"
notebook = "^7.0.3"
pytest = "^7.2.0"
ruff = "^0.1.5"

[tool.ruff]
# see: https://docs.astral.sh/ruff/configuration/#using-pyprojecttoml
fixable = ["I", "E", "W"]
select = ["I", "E", "W"]

line-length = 120

# Assume Python 3.9
target-version = "py39"

# [tool.black]
# target-version = ["py39"]
# line-length = 120
# skip-string-normalization = true

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]
