[tool.poetry]
name = "bms-monitor-sam"
version = "0.2.0"
description = ""
authors = ["Yukihiro Okada <yuokada@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.26.41"
requests = "^2.25"

[tool.poetry.dev-dependencies]
aws-sam-cli = "^1.66.0"
pytest = "^7.4.0"
notebook = "^6.4.12"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
