[tool.poetry]
name = "bms-monitor-sam"
version = "0.2.0"
description = ""
authors = ["Yukihiro Okada <yuokada@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.26.41"
requests = "^2.25"
urllib3 = "<2"

[tool.poetry.group.dev.dependencies]
aws-sam-cli = "^1.103.0"
pytest = "^7.2.0"
notebook = "^7.0.3"
ruff = "^0.1.5"

[tool.ruff]
# see: https://docs.astral.sh/ruff/configuration/#using-pyprojecttoml
select  = ["I", "E", "W", "F"]
fixable = ["I", "E", "W", "F"]

line-length = 120

# Assume Python 3.9
target-version = "py39"

[tool.ruff.format]
# instead of "skip-string-normalization = true"
# see: https://github.com/astral-sh/ruff/issues/7525
quote-style = "double"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
