version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "BmsMonitorBySam"
# s3_bucket    = "aws-sam-cli-managed-default-samclisourcebucket-1l90wfgmezt26"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cnzbjwehiaa9"
s3_prefix = "bms-monitor-by-sam"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
