version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "bms-monitor-development"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cnzbjwehiaa9"
s3_prefix = "bms-monitor"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
