version = 0.1
[default]

[default.global.parameters]
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-cnzbjwehiaa9"
s3_prefix = "bms-monitor"
stack_name = "bms-monitor-development"
region = "ap-northeast-1"

# [default.package]
# [default.package.parameters]

[default.deploy]
[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
