AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bms-monitor

  SAM Template for bms-monitor

Metadata:
  AWS::ServerlessRepo::Application:
    Name: BmsMonitorBySam
    Description: this application is for private
    SpdxLicenseId: Apache-2.0
    Author: Yukihiro Okada
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['bms', 'private']
    SemanticVersion: 0.0.1
    HomePageUrl: https://github.com/y-leisures/http_check-monitor
    SourceCodeUrl: https://github.com/y-leisures/http_check-monitor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    Tags:
      cdk: "false"
      sam: "true"
      system: bms
      repository:  http_check-monitor

Parameters:
  Stage:
    Type: String
    AllowedValues:
      - development
      - staging
      - production
    Default: development
    Description: Stage in which the application will be deployed. Allowed values [development, staging, production]

Mappings:
  StageMapping:
    development:
      Alias: dev
      LogLevelMapping: DEBUG
      FunctionName: "bms-dev-http-monitor"
    staging:
      Alias: stg
      LogLevelMapping: DEBUG
      FunctionName: "bms-stg-http-monitor"
    production:
      Alias: prod
      LogLevelMapping: INFO
      FunctionName: "bms-prod-http-monitor"


Resources:
  BmsMonitoringSnsTopic:
    # see: https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html
    Type: AWS::SNS::Topic
    Properties:
      # ContentBasedDeduplication: false
      # DisplayName: String
      FifoTopic: false
      Subscription:
        - Endpoint: callistoiv+aws@gmail.com
          Protocol: EMAIL
      Tags:
        - Key: cdk
          Value: "false"
        - Key: sam
          Value: "true"
      TopicName: !Sub "bms-${Stage}-monitoring"

  BmsCheckWebsitePeriodicallyFun:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub
        - "bms-${Alias}-http-monitor"
        - { "Alias": !FindInMap [ StageMapping, !Ref Stage, Alias]}
      CodeUri: check_website/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::949140100595:role/service-role/monitor_bms-role-zswvtb9u
      Events:
        # The length of "BmsCheckWebsitePeriodicallyFunCheckWebsiteScheduledEventLambdaTarget" is 71
        Event1:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
      Environment:
        Variables:
          MONITOR_URL: http://b-ms.info/
      # see: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventinvokeconfiguration.html
      EventInvokeConfig:
        # MaximumEventAgeInSeconds: 60
        MaximumRetryAttempts: 1
        DestinationConfig:
          OnFailure:
            Type: SNS
            # Destination: arn:aws:sns:us-east-1:949140100595:NotifyMe
            # Destination: !GetAtt BmsMonitoringSnsTopic.Arn
            Properties:
              Topic:
                Ref: BmsMonitoringSnsTopic
          # OnSuccess:
          #   Type: SNS
          #   Destination:
          #     Ref: DestinationSNS       # Arn of an SNS topic declared in the tempate file

  BmsMonitoringLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${BmsCheckWebsitePeriodicallyFun}
      RetentionInDays: 30

# see: https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
# see: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
Outputs:
  BmsCheckWebsitePeriodicallyFun:
    Description: "CheckWebsite Periodically Lambda Function ARN"
    Value: !GetAtt BmsCheckWebsitePeriodicallyFun.Arn

  # BmsMonitoringSnsTopic:
  #   Description: "BmsMonitoringSnsTopic SNS Topic ARN"
  #   Value: !GetAtt BmsMonitoringSnsTopic.Arn
