AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bms-monitor

  Sample SAM Template for bms-monitor

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  BmsCheckWebsitePeriodicallyFun:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: bms-monitor-by-sam
      CodeUri: check_website/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: arn:aws:iam::949140100595:role/service-role/monitor_bms-role-zswvtb9u
      Events:
        # The length of "BmsCheckWebsitePeriodicallyFunCheckWebsiteScheduledEventLambdaTarget" is 71
        Event1:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
      Environment:
        Variables:
          MONITOR_URL: http://b-ms.info/
      # see: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-eventinvokeconfiguration.html
      EventInvokeConfig:
        # MaximumEventAgeInSeconds: 60
        MaximumRetryAttempts: 1
        DestinationConfig:
          OnFailure:
            Type: SNS
            Destination: arn:aws:sns:us-east-1:949140100595:NotifyMe

  BmsMonitoringLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${BmsCheckWebsitePeriodicallyFun}
      RetentionInDays: 30

# see: https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
# see: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/outputs-section-structure.html
Outputs:
  BmsCheckWebsitePeriodicallyFun:
    Description: "CheckWebsite Periodically Lambda Function ARN"
    Value: !GetAtt BmsCheckWebsitePeriodicallyFun.Arn
