---
name: 'Common Action'
description: 'Common Action'
runs:
  using: 'composite'
  steps:
    - name: Install uv
      shell: bash
      run: |
        pip3 install -q uv
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      shell: bash
      run: |
        uv sync --group dev
