---
name: python coding style check

# on: [push, pull_request]
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_files:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed_files.outputs.changed_files }}
    steps:
      - uses: actions/checkout@v4
      - name: List Changed Python Files
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.py$' || true)
          # changed_files=$(git diff --name-only master... | grep '\.py$' || true)
          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
        id: changed_files

  run_formatter:
    needs: check_files
    runs-on: ubuntu-latest
    if: needs.check_files.outputs.changed_files != ''
    steps:
      - uses: actions/checkout@v4
      - name: List Changed Python Files
        run: |
          git fetch origin ${{ github.event.pull_request.base.sha }}
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.py$' || true)
          # changed_files=$(git diff --name-only master... | grep '\.py$' || true)
          echo "changed_files=$changed_files" >> $GITHUB_OUTPUT
        id: changed_files
      - uses: ./.github/actions/common-action
      - name: Run ruff
        run: |
          uv run ruff format --check --diff "${{ steps.changed_files.outputs.changed_files }}"
          uv run ruff check           "${{ steps.changed_files.outputs.changed_files }}"

  mypy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/common-action
      - name: Run mypy
        run: |
          uv run mypy --config pyproject.toml check_website
