---
# see: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/deploying-using-github.html
name: publish the application with github actions to Serverless Application Repository

on:
  push:
    tags:
      - '*' # Push events to every tag not containing /
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - run: sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-cnzbjwehiaa9
      - run: sam publish --semantic-version ${{ steps.get_version.outputs.VERSION }} -t packaged.yaml --region ap-northeast-1
