---
# see: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/deploying-using-github.html
name: deploy the application with github actions

on:
  push:
    branches:
      - master
    paths-ignore:
      - notebooks/
      - layers/
  pull_request:
    branches:
      - master

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: sam build --use-container
      - run: sam validate --lint --template-file template.yaml
      - run: sam deploy --stack-name bms-monitor-development --no-confirm-changeset --no-fail-on-empty-changeset --tags 'Owner="Yukihiro Okada" service=bms-monitoring cdk=true repository="https://github.com/y-leisures/http_check-monitor"' --parameter-overrides "WebhookUrl=${{ secrets.SLACK_HOOK_URL }}"

  validation:
    if: contains(github.event_name, 'pull_request')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: sam build --use-container
      - run: sam validate --lint --template-file template.yaml
      - name: Execute dry-run
        run: |
          sam package --debug --config-file samconfig.toml --output-template-file deploy-template.yaml
          sam deploy --config-file samconfig.toml --template-file deploy-template.yaml --no-execute-changeset \
              --parameter-overrides "WebhookUrl=${{ secrets.SLACK_HOOK_URL }}"
