# see: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/deploying-using-github.html
name: publish the application with github actions to Serverless Application Repository

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - run: |
        sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-cnzbjwehiaa9
      - run: |
        sam publish --semantic-version 0.1.0 -t packaged.yaml --region ap-northeast-1
